name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up our JDK environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Install dependencies and run JVM tests
        run: ./gradlew jvmTest koverXmlReport
      - name: Run macOS native tests
        if: runner.os == 'macOS'
        run: ./gradlew macosArm64Test
      - name: Run Linux native tests
        if: runner.os == 'Linux'
        run: ./gradlew linuxX64Test
      - name: Run Windows native tests
        if: runner.os == 'Windows'
        run: ./gradlew mingwX64Test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
